name: "EC2 Deploy"
on:
  push:
    branches:
      - main
  workflow_dispatch: # This line enables the manual run trigger with the "Run workflow" button

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: cardarenafe
  ECR_REGISTRY: 729926669123.dkr.ecr.ap-south-1.amazonaws.com
  IMAGE_TAG: latest

jobs:
  deploy-image:
    runs-on: ubuntu-latest

    steps:
  
      - name: Checkout
        uses: actions/checkout@v3
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
  
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
  
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        id: deploy-ec2
        run: |
          aws ecr get-login-password | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
          sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          sudo docker-compose -f /home/ec2-user/fe-docker-compose.yml down --remove-orphans
          sudo docker-compose -f /home/ec2-user/fe-docker-compose.yml up -d
